version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: kyc-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/backend/app
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kyc-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend
